### ISSUE TITLE
Exiting a shell

### ISSUE THREAD

**Issue by wlingke** [rma4ok/grunt-bg-shell#14]
I wasn't sure how to do this but how can I programatically close a shell? For example, say I start a server in one task, then I want to run some E2E tests, then I want to exit the server. How can I do that?

Thanks!

**Comment by DustinJSilk** [comment]
Im also currently in the same position. I have a python server and the exact same gruntfile config.. It works great in that child processes keep running in the background. However at some point id need to kill those processes. Potentially when i rerun grunt.. The only way i would normally end the process is by hitting Ctrl+C.

**Comment by re1ro** [comment]
@DustinJSilk is there a chance you could share that `application.py` with me? some simple version that doesn't get ended
