### ISSUE TITLE
kill created child process on exit

### ISSUE THREAD

**Issue by aemonge** [rma4ok/grunt-bg-shell#15]
when quiting grunt, it should kill all background process

**Comment by aemonge** [comment]
Wops !!!!!! Sorry @rma4ok , the error has been solved, and I totally forgot to tell you.

**Comment by re1ro** [comment]
@aemonge  No problem at all =) Are you still using the library by the way?

**Comment by aemonge** [comment]
Nop,we moved to gulp. /:
