### ISSUE TITLE
Passing arguments to command

### ISSUE THREAD

**Issue by shashwatblack** [rma4ok/grunt-bg-shell#19]
grunt-shell allows passing arguments to commands to be run. Is there a way to do so in grunt-bg-shell as well?

**Comment by re1ro** [comment]
@shashwatblack  I think you can achieve it using cmd function 

```
bgShell: {
  lsTasks: {
    cmd: function(){return 'ls ' + YOUR_PASSED_ARGS}
  }     
}
```

could you provide some code of what are you trying to do?
