### ISSUE TITLE
no grunt template vars resolving in string

### ISSUE THREAD

**Issue by monsdroid** [rma4ok/grunt-bg-shell#20]
Hi,

thanks for the plugin!
I switched from grunt-.shell-spawn, well, because of reasons. 
What i could do in grunt shell was using config properties in the string a command returned. basicaly that grunt template thingy

e.g.

```
command: function (exportConfigFile) {
            return ' \
                java -classpath <%= someVar %>/lib/* \
                -Dlogback.configurationFile=<%=exportConfigFile%>/logback.xml;
        }
```

in your plugin theses vars wont get resolved. instead i get ` java -classpath <%= someVar %>/lib/* ...`

Best regards,
Simon

**Comment by re1ro** [comment]
@monsdroid 
You have a full flexibility of what happens inside of your function. You could try it this way
```js
command: function () {
            return grunt.template.process(' \
                java -classpath <%= someVar %>/lib/* \
                -Dlogback.configurationFile=<%=exportConfigFile%>/logback.xml');
        }
```
